import { projectState } from '$lib/state/project.svelte';
import { artifactState } from '$lib/state/artifact.svelte';
import { CONSULTANTS } from '$lib/constants/consultants';
import { toastState } from '$lib/state/toast.svelte';
import type { PhaseNumber } from '$lib/types/project';
import type { Artifact } from '$lib/types/artifact';

function groupByPhase(artifacts: Artifact[]): Map<PhaseNumber, Artifact[]> {
  const map = new Map<PhaseNumber, Artifact[]>();
  for (const a of artifacts) {
    const list = map.get(a.phaseNumber) || [];
    list.push(a);
    map.set(a.phaseNumber, list);
  }
  return map;
}

function buildDocBundle(): string {
  const project = projectState.currentProject;
  if (!project) return '';

  const arts = artifactState.artifacts.filter((a) => a.projectId === project.id);
  const grouped = groupByPhase(arts);
  const lines: string[] = [];

  lines.push(`# ${project.name}`);
  lines.push(`> ${project.description || 'No description'}`);
  lines.push(`> Generated by CATALYST on ${new Date().toLocaleDateString()}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Table of contents
  lines.push('## Table of Contents');
  for (let p = 1; p <= 7; p++) {
    const phase = p as PhaseNumber;
    const c = CONSULTANTS[phase];
    const count = grouped.get(phase)?.length ?? 0;
    if (count > 0) {
      lines.push(`- **Phase ${p}: ${c.description}** (${count} artifacts)`);
    }
  }
  lines.push('');

  // Phase sections
  for (let p = 1; p <= 7; p++) {
    const phase = p as PhaseNumber;
    const phaseArts = grouped.get(phase);
    if (!phaseArts || phaseArts.length === 0) continue;

    const c = CONSULTANTS[phase];
    lines.push(`---`);
    lines.push('');
    lines.push(`## Phase ${p}: ${c.description}`);
    lines.push(`*Consultant: ${c.name} — ${c.title}*`);
    lines.push('');

    for (const art of phaseArts) {
      lines.push(`### ${art.title}`);
      lines.push(`*Type: ${art.type} | Version: ${art.version} | Updated: ${art.updatedAt}*`);
      if (art.isStale) lines.push('> ⚠️ This artifact may be stale');
      lines.push('');
      lines.push(art.content);
      lines.push('');
    }
  }

  return lines.join('\n');
}

function buildCodeScaffold(): string {
  const project = projectState.currentProject;
  if (!project) return '';

  const arts = artifactState.artifacts.filter((a) => a.projectId === project.id);
  const codeArts = arts.filter((a) => ['source-code', 'ci-config', 'test-suite'].includes(a.type));
  if (codeArts.length === 0) return '';

  const lines: string[] = [];
  lines.push(`# ${project.name} — Code Scaffold`);
  lines.push('');

  for (const art of codeArts) {
    lines.push(`## ${art.title}`);
    lines.push('```');
    lines.push(art.content);
    lines.push('```');
    lines.push('');
  }

  return lines.join('\n');
}

export async function exportDocBundle(): Promise<void> {
  const bundle = buildDocBundle();
  if (!bundle) {
    toastState.warning('No project selected to export');
    return;
  }
  await navigator.clipboard.writeText(bundle);
  toastState.success('Documentation bundle copied to clipboard');
}

export async function exportCodeScaffold(): Promise<void> {
  const scaffold = buildCodeScaffold();
  if (!scaffold) {
    toastState.warning('No code artifacts found to export');
    return;
  }
  await navigator.clipboard.writeText(scaffold);
  toastState.success('Code scaffold copied to clipboard');
}

export async function exportAll(): Promise<void> {
  const docs = buildDocBundle();
  const code = buildCodeScaffold();
  const full = [docs, code ? '\n---\n\n' + code : ''].join('');
  if (!full.trim()) {
    toastState.warning('Nothing to export');
    return;
  }
  await navigator.clipboard.writeText(full);
  toastState.success('Full project export copied to clipboard');
}
